/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarketapp;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author User
 */
public class SupermarketProgram extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    private Hashtable<String,Component> TabComponent = new Hashtable();

    private ImageIcon ProductImage;
    JFileChooser ProductImageFileChooser;
    private DefaultListModel ProductDisplayedList;
    private DefaultListModel OrderProductDisplayedList;
    
    private ProductList Products;
    private UserList Users;
    private User CurrentUser;
    
    public SupermarketProgram() {
        
        BufferedReader Productbin;
        try {
            Productbin = new BufferedReader(new FileReader("Products.txt"));
            Products=new ProductList();
            Products.LoadFromFile(Productbin);
            Productbin.close();
            Productbin=null;
        } catch (IOException ex) {
            
        }
        
        ProductDisplayedList=new DefaultListModel();
        OrderProductDisplayedList=new DefaultListModel();
        ProductImage = new ImageIcon("Milk.png");
        ProductImageFileChooser = new JFileChooser(System. getProperty("user.dir"));
        ProductImageFileChooser.setDialogTitle("Select an image");
        ProductImageFileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG and JPG images", "png", "jpg");
        ProductImageFileChooser.addChoosableFileFilter(filter);
        
        initComponents();
        
        Users=new UserList();
        
        String TabName;
        for (int i=0;i<Tabs.getTabCount();i++){
            TabName= Tabs.getTitleAt(i);
            switch (TabName){
                case "Owner-Menu":
                case "Customer-Menu":
                case "Products":
                case "Add Product":
                case "Order Products":
                //case "Account":
                    TabComponent.put(TabName,Tabs.getComponentAt(i));
                    Tabs.remove(i);
                    i--;
                    break;
            }
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        Login = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        UserName = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        OwnerMenu = new javax.swing.JPanel();
        ViewProductsPageButton = new javax.swing.JButton();
        AddNewProductPageButton = new javax.swing.JButton();
        ReOrderProducts = new javax.swing.JButton();
        CustomerMenu = new javax.swing.JPanel();
        ChoosePageProductButton = new javax.swing.JButton();
        ChoosePageProductButton1 = new javax.swing.JButton();
        OwnerProducts = new javax.swing.JPanel();
        ProductNamesScrollBar = new javax.swing.JScrollPane();
        ProductNames = new javax.swing.JList(ProductDisplayedList);
        DisplayProductDetailsButton = new javax.swing.JButton();
        ProductDetailsScrollBar = new javax.swing.JScrollPane();
        ProductDetails = new javax.swing.JTextArea();
        ImageIcon = new JLabel(ProductImage);
        EditProductButton = new javax.swing.JButton();
        AddProduct = new javax.swing.JPanel();
        ProductNameTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ProductExpiryDateTextBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ProductWeightTextBox = new javax.swing.JTextField();
        ProductPriceTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProductCategoryTextBox = new javax.swing.JTextField();
        ProductMaximumLevelStockTextBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ProductIDTextBox = new javax.swing.JTextField();
        AddProductButton = new javax.swing.JButton();
        ProductMinimumLevelStockTextBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ProductImageFileTextBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ProductChooseImageFileButton = new javax.swing.JButton();
        SupplierNameTextBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        DeliveryPolicyTextBox = new javax.swing.JTextField();
        PriceOfDeliveryTextBox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        EditProductButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ProductNamesScrollBar1 = new javax.swing.JScrollPane();
        OrderProductList = new javax.swing.JList(OrderProductDisplayedList);
        OrderProductButton = new javax.swing.JButton();
        OrderProductQuantityTextBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ProductDetailsScrollBar1 = new javax.swing.JScrollPane();
        OrderProductDetails = new javax.swing.JTextArea();
        ProductDetailsOrderButton = new javax.swing.JButton();
        ProgramStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Tabs.setMaximumSize(new java.awt.Dimension(401, 286));
        Tabs.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TabsComponentAdded(evt);
            }
        });

        LoginButton.setText("Log-in");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        UserNameLabel.setText("User Name:");

        PasswordLabel.setText("Password:");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginButton)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameLabel)
                            .addComponent(PasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserName)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameLabel))
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addGap(18, 18, 18)
                .addComponent(LoginButton)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        Tabs.addTab("Log-in", Login);

        ViewProductsPageButton.setText("View Products");
        ViewProductsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductsPageButtonActionPerformed(evt);
            }
        });

        AddNewProductPageButton.setText("Add New Product");
        AddNewProductPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewProductPageButtonActionPerformed(evt);
            }
        });

        ReOrderProducts.setText("Re-Order");
        ReOrderProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReOrderProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OwnerMenuLayout = new javax.swing.GroupLayout(OwnerMenu);
        OwnerMenu.setLayout(OwnerMenuLayout);
        OwnerMenuLayout.setHorizontalGroup(
            OwnerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OwnerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewProductsPageButton)
                    .addComponent(AddNewProductPageButton)
                    .addComponent(ReOrderProducts))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        OwnerMenuLayout.setVerticalGroup(
            OwnerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewProductsPageButton)
                .addGap(18, 18, 18)
                .addComponent(AddNewProductPageButton)
                .addGap(18, 18, 18)
                .addComponent(ReOrderProducts)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        Tabs.addTab("Owner-Menu", OwnerMenu);

        ChoosePageProductButton.setText("View Products");
        ChoosePageProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoosePageProductButtonActionPerformed(evt);
            }
        });

        ChoosePageProductButton1.setText("Order Products");
        ChoosePageProductButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoosePageProductButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerMenuLayout = new javax.swing.GroupLayout(CustomerMenu);
        CustomerMenu.setLayout(CustomerMenuLayout);
        CustomerMenuLayout.setHorizontalGroup(
            CustomerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChoosePageProductButton)
                    .addComponent(ChoosePageProductButton1))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        CustomerMenuLayout.setVerticalGroup(
            CustomerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChoosePageProductButton)
                .addGap(18, 18, 18)
                .addComponent(ChoosePageProductButton1)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        Tabs.addTab("Customer-Menu", CustomerMenu);

        OwnerProducts.setMaximumSize(new java.awt.Dimension(396, 258));
        OwnerProducts.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                OwnerProductsComponentAdded(evt);
            }
        });
        OwnerProducts.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                OwnerProductsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        ProductNames.setMaximumSize(new java.awt.Dimension(100, 236));
        ProductNames.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ProductNamesValueChanged(evt);
            }
        });
        ProductNamesScrollBar.setViewportView(ProductNames);

        DisplayProductDetailsButton.setText("Display Product Details");
        DisplayProductDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayProductDetailsButtonActionPerformed(evt);
            }
        });

        ProductDetails.setColumns(20);
        ProductDetails.setRows(5);
        ProductDetails.setMaximumSize(new java.awt.Dimension(270, 141));
        ProductDetailsScrollBar.setViewportView(ProductDetails);

        ImageIcon.setMaximumSize(new java.awt.Dimension(89, 89));
        ImageIcon.setMinimumSize(new java.awt.Dimension(89, 89));

        EditProductButton.setText("Edit Product");
        EditProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OwnerProductsLayout = new javax.swing.GroupLayout(OwnerProducts);
        OwnerProducts.setLayout(OwnerProductsLayout);
        OwnerProductsLayout.setHorizontalGroup(
            OwnerProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductNamesScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OwnerProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OwnerProductsLayout.createSequentialGroup()
                        .addGroup(OwnerProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DisplayProductDetailsButton)
                            .addComponent(EditProductButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(ImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ProductDetailsScrollBar))
                .addContainerGap())
        );
        OwnerProductsLayout.setVerticalGroup(
            OwnerProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerProductsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(OwnerProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductNamesScrollBar)
                    .addGroup(OwnerProductsLayout.createSequentialGroup()
                        .addGroup(OwnerProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OwnerProductsLayout.createSequentialGroup()
                                .addComponent(EditProductButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DisplayProductDetailsButton))
                            .addComponent(ImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductDetailsScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Tabs.addTab("Products", OwnerProducts);

        jLabel1.setText("Product Name");

        jLabel2.setText("Expriy Date");

        jLabel3.setText("Weight");

        jLabel4.setText("Price");

        jLabel5.setText("Product Category");

        jLabel6.setText("Max level of stock");

        jLabel8.setText("Product ID");

        AddProductButton.setText("Add Product");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Min level of stock");

        ProductImageFileTextBox.setEnabled(false);

        jLabel10.setText("Image File");

        ProductChooseImageFileButton.setText("Choose File");
        ProductChooseImageFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductChooseImageFileButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel11.setText("Supplier");

        jLabel12.setText("Name");

        jLabel13.setText("Delivery Policy");

        jLabel14.setText("Price of delivery");

        EditProductButton1.setText("Edit Product");
        EditProductButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProductButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddProductLayout = new javax.swing.GroupLayout(AddProduct);
        AddProduct.setLayout(AddProductLayout);
        AddProductLayout.setHorizontalGroup(
            AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddProductLayout.createSequentialGroup()
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddProductLayout.createSequentialGroup()
                                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProductNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(ProductPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddProductLayout.createSequentialGroup()
                                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(ProductExpiryDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(ProductCategoryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddProductLayout.createSequentialGroup()
                                .addComponent(ProductImageFileTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProductChooseImageFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(ProductMinimumLevelStockTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(AddProductButton)
                    .addGroup(AddProductLayout.createSequentialGroup()
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddProductLayout.createSequentialGroup()
                                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(ProductWeightTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(ProductMaximumLevelStockTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditProductButton1)))
                            .addComponent(ProductIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(AddProductLayout.createSequentialGroup()
                                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(SupplierNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(PriceOfDeliveryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(DeliveryPolicyTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        AddProductLayout.setVerticalGroup(
            AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AddProductLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddProductLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProductExpiryDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddProductLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProductCategoryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddProductLayout.createSequentialGroup()
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductImageFileTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductChooseImageFileButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddProductLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addComponent(ProductMinimumLevelStockTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddProductLayout.createSequentialGroup()
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductWeightTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ProductMaximumLevelStockTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(AddProductLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PriceOfDeliveryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddProductLayout.createSequentialGroup()
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddProductLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeliveryPolicyTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddProductButton)
                    .addComponent(EditProductButton1)))
        );

        Tabs.addTab("Add Product", AddProduct);

        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        OrderProductList.setMaximumSize(new java.awt.Dimension(100, 236));
        OrderProductList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                OrderProductListValueChanged(evt);
            }
        });
        ProductNamesScrollBar1.setViewportView(OrderProductList);

        OrderProductButton.setText("Order");
        OrderProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderProductButtonActionPerformed(evt);
            }
        });

        OrderProductQuantityTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderProductQuantityTextBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantity");

        OrderProductDetails.setColumns(20);
        OrderProductDetails.setRows(5);
        OrderProductDetails.setMaximumSize(new java.awt.Dimension(270, 141));
        ProductDetailsScrollBar1.setViewportView(OrderProductDetails);

        ProductDetailsOrderButton.setText("Show Product Details");
        ProductDetailsOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductDetailsOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductNamesScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(OrderProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OrderProductQuantityTextBox))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductDetailsScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ProductDetailsOrderButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ProductNamesScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProductDetailsOrderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderProductQuantityTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OrderProductButton))
                            .addComponent(ProductDetailsScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        Tabs.addTab("Order Products", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProgramStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProgramStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        //TODO implement user varifcation 
        CurrentUser=Users.ValidateUser(UserName.getText(), Password.getText());
        if(CurrentUser==null){
            ProgramStatus.setText("Invalid User");
        }
        else if(CurrentUser.IsCustomer()){
            AddMenu("Customer-Menu");
            ProgramStatus.setText("Customer Logged In "+CurrentUser.GetUserName());
        }else if(CurrentUser.IsOwner()){
            AddMenu("Owner-Menu");
            ProgramStatus.setText("Owner Logged In");
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RefreshMenuTabs(){
        for (int i=0;i<Tabs.getTabCount();i++){
            switch (Tabs.getTitleAt(i)){
                case "Owner-Menu":
                case "Customer-Menu":
                case "Products":
                case "Add Product":
                case "Order Products":
                //case "Account":
                    Tabs.remove(i);
                    i--;
                    break;
            }
        }
    }
    
    private void AddMenu(String TabName){
        RefreshMenuTabs();
        Tabs.add(TabName,TabComponent.get(TabName));
        Tabs.setSelectedIndex(1);
    }
    
    private void AddUserTab(String TabName,int Index){
        Tabs.add(TabName,TabComponent.get(TabName));
        Tabs.setSelectedIndex(Index);
    }
    
    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void AddNewProductPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewProductPageButtonActionPerformed
        for (int i=0;i<Tabs.getTabCount();i++){
            switch (Tabs.getTitleAt(i)){
                case "Products":
                case "Add Product":
                case "Order Products":
                //case "Account":
                    Tabs.remove(i);
                    i--;
                    break;
            }
        }
        AddUserTab("Add Product",2);
        AddProductButton.setEnabled(true);
        EditProductButton1.setEnabled(false);
        ProductIDTextBox.setEnabled(true);
    }//GEN-LAST:event_AddNewProductPageButtonActionPerformed

    private void DisplayProductDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayProductDetailsButtonActionPerformed
        String ID;
        ProductDetails.setText(null);
        ID=getIDFromList(ProductNames);
        if(ID==null){
        }else{
            CurrentUser.ViewProductDetails(ID,Products,ProductDetails);
        }
    }//GEN-LAST:event_DisplayProductDetailsButtonActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        try{
            CurrentUser.AddProduct(ProductIDTextBox.getText(), ProductNameTextBox.getText(), 
                    ProductPriceTextBox.getText(), ProductWeightTextBox.getText(), 
                    ProductExpiryDateTextBox.getText(), ProductImageFileTextBox.getText(), 
                    ProductCategoryTextBox.getText(), ProductMaximumLevelStockTextBox.getText(), 
                    ProductMinimumLevelStockTextBox.getText(),Products,SupplierNameTextBox.getText(),
                    DeliveryPolicyTextBox.getText(),PriceOfDeliveryTextBox.getText());
            ProductDisplayedList.clear();
            CurrentUser.ViewProducts(Products,ProductDisplayedList);
            CurrentUser.ViewProductsForOrdering(Products,OrderProductDisplayedList);
            ProgramStatus.setText("Product was added");
        }catch(IllegalArgumentException iae){
            ProgramStatus.setText(iae.getMessage());
        }
    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        try {
            FileWriter Writer = new FileWriter("Products.txt");
            Products.ClearFile(Writer);
            Products.SaveToFile(Writer);
            Writer.flush();
            Writer.close();
            Writer=null;
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_formWindowClosing

    private void ProductChooseImageFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductChooseImageFileButtonActionPerformed
        int returnValue = ProductImageFileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String path = ProductImageFileChooser.getSelectedFile().getPath();
                if((new ImageIcon(path).getIconWidth()<=89)&&(new ImageIcon(path).getIconHeight()<=89)){
                    ProductImageFileTextBox.setText(path);
                    ProgramStatus.setText("Image was selected");
                }else{
                    ProgramStatus.setText("Image can't be larger than 89x89");
                }
        }
    }//GEN-LAST:event_ProductChooseImageFileButtonActionPerformed

    private void ProductNamesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ProductNamesValueChanged
        String ID=getIDFromList(ProductNames);
        if(ID!=null){
            Product SelectedProduct = Products.Search(ID);
            SelectedProduct.DisplayImage(ImageIcon);
            if(SelectedProduct.getOutOfStock()){
                if(CurrentUser.IsOwner()){
                    ProgramStatus.setText("Out Of Stock NEED TO RE-ORDER");
                }else{
                    ProgramStatus.setText("Out Of Stock");
                }
            }else{ProgramStatus.setText("In Stock");}
        }
    }//GEN-LAST:event_ProductNamesValueChanged

    private void ViewProductsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductsPageButtonActionPerformed
        for (int i=0;i<Tabs.getTabCount();i++){
            switch (Tabs.getTitleAt(i)){
                case "Products":
                case "Add Product":
                case "Order Products":
                //case "Account":
                    Tabs.remove(i);
                    i--;
                    break;
            }
        }
        AddUserTab("Products",2);
    }//GEN-LAST:event_ViewProductsPageButtonActionPerformed

    private void ChoosePageProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoosePageProductButtonActionPerformed
        for (int i=0;i<Tabs.getTabCount();i++){
            switch (Tabs.getTitleAt(i)){
                case "Products":
                case "Add Product":
                case "Order Products":
                //case "Account":
                    Tabs.remove(i);
                    i--;
                    break;
            }
        }
        AddUserTab("Products",2);
    }//GEN-LAST:event_ChoosePageProductButtonActionPerformed

    private void TabsComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TabsComponentAdded
        
    }//GEN-LAST:event_TabsComponentAdded

    private void OwnerProductsComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_OwnerProductsComponentAdded

    }//GEN-LAST:event_OwnerProductsComponentAdded

    private void OwnerProductsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_OwnerProductsAncestorAdded
        if(CurrentUser.IsOwner()){
            EditProductButton.setEnabled(true);
        }else{
            EditProductButton.setEnabled(false);
        }
        ProductDetails.setText("");
        ProductDisplayedList.clear();
        CurrentUser.ViewProducts(Products, ProductDisplayedList);
        
    }//GEN-LAST:event_OwnerProductsAncestorAdded

    private void OrderProductListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_OrderProductListValueChanged
        
    }//GEN-LAST:event_OrderProductListValueChanged

    private void OrderProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderProductButtonActionPerformed
        try{
            SimpleDateFormat DateFormat=new SimpleDateFormat("dd/MM/yyyy");
            Date DateOfOrder = CurrentUser.Order(getIDFromList(OrderProductList), Products, OrderProductQuantityTextBox.getText());
            ProgramStatus.setText("The Date Of Delivery Will Be"+DateFormat.format(DateOfOrder));
        }catch(IllegalArgumentException iae){
            ProgramStatus.setText(iae.getMessage());
        }
        OrderProductDisplayedList.clear();
        CurrentUser.ViewProductsForOrdering(Products,OrderProductDisplayedList);
    }//GEN-LAST:event_OrderProductButtonActionPerformed

    private void ReOrderProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReOrderProductsActionPerformed
        for (int i=0;i<Tabs.getTabCount();i++){
            switch (Tabs.getTitleAt(i)){
                case "Products":
                case "Add Product":
                case "Order Products":
                //case "Account":
                    Tabs.remove(i);
                    i--;
                    break;
            }
        }
        AddUserTab("Order Products",2);
    }//GEN-LAST:event_ReOrderProductsActionPerformed

    private void ChoosePageProductButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoosePageProductButton1ActionPerformed
        for (int i=0;i<Tabs.getTabCount();i++){
            switch (Tabs.getTitleAt(i)){
                case "Products":
                case "Add Product":
                case "Order Products":
                //case "Account":
                    Tabs.remove(i);
                    i--;
                    break;
            }
        }
        AddUserTab("Order Products",2);
    }//GEN-LAST:event_ChoosePageProductButton1ActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        OrderProductDisplayedList.clear();
        CurrentUser.ViewProductsForOrdering(Products,OrderProductDisplayedList);
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void OrderProductQuantityTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderProductQuantityTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderProductQuantityTextBoxActionPerformed

    private void EditProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProductButtonActionPerformed
        if((getIDFromList(ProductNames))!=null){
            Tabs.add("Edit Product",TabComponent.get("Add Product"));
            Tabs.setSelectedIndex(3);
            AddProductButton.setEnabled(false);
            EditProductButton1.setEnabled(true);
            ProductIDTextBox.setEnabled(false);
            
            Product NewProduct= CurrentUser.ViewProductDetailsForEdit(getIDFromList(ProductNames), Products);
            
            ProductNameTextBox.setText(NewProduct.getProductName());
            ProductExpiryDateTextBox.setText(NewProduct.getExpiryDate());
            ProductWeightTextBox.setText(NewProduct.getWeight());
            ProductIDTextBox.setText(NewProduct.getStringID());
            ProductPriceTextBox.setText(NewProduct.getPrice());
            ProductCategoryTextBox.setText(NewProduct.getProductCatagory());
            ProductMaximumLevelStockTextBox.setText(NewProduct.getMaxLevelOfStock());
            ProductImageFileTextBox.setText(NewProduct.getImageFile());
            ProductMinimumLevelStockTextBox.setText(NewProduct.getMinLevelOfStock());
            SupplierNameTextBox.setText(NewProduct.getSupplierName());
            PriceOfDeliveryTextBox.setText(NewProduct.getSupplierPrice());
            DeliveryPolicyTextBox.setText(NewProduct.getDeliveryPolicy());
        }
    }//GEN-LAST:event_EditProductButtonActionPerformed

    private void ProductDetailsOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductDetailsOrderButtonActionPerformed
        try{
            String ID= getIDFromList(OrderProductList);
            if(ID==null){
                OrderProductDetails.setText("null");
            }else{
                OrderProductDetails.setText("");
                CurrentUser.ViewProductDetailsForOrdering(ID,Products, OrderProductDetails);
            }
        }catch(UnsupportedOperationException uoe){
            OrderProductDetails.setText(uoe.getMessage());
        }
    }//GEN-LAST:event_ProductDetailsOrderButtonActionPerformed

    private void EditProductButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProductButton1ActionPerformed
        try{
        CurrentUser.EditProduct(ProductIDTextBox.getText(), ProductNameTextBox.getText(), 
                ProductPriceTextBox.getText(), ProductWeightTextBox.getText(), 
                ProductExpiryDateTextBox.getText(), ProductImageFileTextBox.getText(),
                ProductCategoryTextBox.getText(), ProductMaximumLevelStockTextBox.getText(),
                ProductMinimumLevelStockTextBox.getText(), Products, SupplierNameTextBox.getText(),
                DeliveryPolicyTextBox.getText(), PriceOfDeliveryTextBox.getText());
        }catch(IllegalArgumentException iae){
            ProgramStatus.setText(iae.getMessage());
        }
    }//GEN-LAST:event_EditProductButton1ActionPerformed
    
    private String getIDFromList(JList ProductList){
        String[] ListRowParts;
        String ListRow;
        if((ListRow =(String) ProductList.getSelectedValue())==(null)){
            ProgramStatus.setText("No Product Found");
            return null;
        }
        ListRowParts=(ListRow.split("-"));
        return ListRowParts[1];
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewProductPageButton;
    private javax.swing.JPanel AddProduct;
    private javax.swing.JButton AddProductButton;
    private javax.swing.JButton ChoosePageProductButton;
    private javax.swing.JButton ChoosePageProductButton1;
    private javax.swing.JPanel CustomerMenu;
    private javax.swing.JTextField DeliveryPolicyTextBox;
    private javax.swing.JButton DisplayProductDetailsButton;
    private javax.swing.JButton EditProductButton;
    private javax.swing.JButton EditProductButton1;
    private javax.swing.JLabel ImageIcon;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton OrderProductButton;
    private javax.swing.JTextArea OrderProductDetails;
    private javax.swing.JList<String> OrderProductList;
    private javax.swing.JTextField OrderProductQuantityTextBox;
    private javax.swing.JPanel OwnerMenu;
    private javax.swing.JPanel OwnerProducts;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PriceOfDeliveryTextBox;
    private javax.swing.JTextField ProductCategoryTextBox;
    private javax.swing.JButton ProductChooseImageFileButton;
    private javax.swing.JTextArea ProductDetails;
    private javax.swing.JButton ProductDetailsOrderButton;
    private javax.swing.JScrollPane ProductDetailsScrollBar;
    private javax.swing.JScrollPane ProductDetailsScrollBar1;
    private javax.swing.JTextField ProductExpiryDateTextBox;
    private javax.swing.JTextField ProductIDTextBox;
    private javax.swing.JTextField ProductImageFileTextBox;
    private javax.swing.JTextField ProductMaximumLevelStockTextBox;
    private javax.swing.JTextField ProductMinimumLevelStockTextBox;
    private javax.swing.JTextField ProductNameTextBox;
    private javax.swing.JList<String> ProductNames;
    private javax.swing.JScrollPane ProductNamesScrollBar;
    private javax.swing.JScrollPane ProductNamesScrollBar1;
    private javax.swing.JTextField ProductPriceTextBox;
    private javax.swing.JTextField ProductWeightTextBox;
    private javax.swing.JLabel ProgramStatus;
    private javax.swing.JButton ReOrderProducts;
    private javax.swing.JTextField SupplierNameTextBox;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JButton ViewProductsPageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
